project:
  type: website
  preview: 
      port: 1313

website:
  title: "Jin Saeki Ko"
  site-url: "https://jinsko.com"
  description: "A website for thinking."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - href: books.qmd
        text: Books
  page-navigation: true
  search: false

# In your _quarto.yml file

format:
  html:
    respect-user-color-scheme: true
    theme: lightly
    toc-title: "Table of Contents"
    css: [styles.css, mobile.css]
    toc: false
    toc-depth: 3
    toc-expand: true

execute:
  freeze: auto

resources:
  - "static/*"